13309zadanie1/Models/ErrorViewModel.cs
using System;

namespace _13309zadanie1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

13309zadanie1/Models/Plyty.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _13309zadanie1.Models
{
    public class Plyty
    {
        [HiddenInput]
        public int Id { get; set; }
        [Required(ErrorMessage = "Proszę podać szerokość płyty")]
        [Range(0, 2100, ErrorMessage = "Szerokość płyty od 0 do 2100")]
        public int Szerokosc { get; set; }
        [Required(ErrorMessage = "Proszę podać wysokość płyty")]
        [Range(0, 2850, ErrorMessage = "Wysokość płyty od 0 do 2850")]
        public int Wysokosc { get; set; }
        [RegularExpression(@"\d+(?:,\d{1,2})?", ErrorMessage = "Prosze podac liczbe z max 2 miejscami po przecinku")]
        [Required(ErrorMessage = "Proszę podać cenę za 1m^2")]
        [Range(0, 99999.99, ErrorMessage = "Cena od 0 do 99999,99")]
        public decimal Cena { get; set; }
        [Required(ErrorMessage = "Proszę podać ilość płyt")]
        [Range(0, 200, ErrorMessage = "Ilość płyt od 0 do 200")]
        public int Ilosc { get; set; }
    }
}

13309zadanie1/Controllers/HomeController.cs
using _13309zadanie1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace _13309zadanie1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

13309zadanie1/Controllers/PlytyController.cs
using _13309zadanie1.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _13309zadanie1.Controllers
{
    public class PlytyController : Controller
    {
        public static List<Plyty> list = new List<Plyty>() { };
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult Add()
        {
            return View("Add");
        }
        [HttpPost]
        public ActionResult Add(Plyty plyty)
        {
            int index = 0;
            if (ModelState.IsValid)
            {
                plyty.Id = index++;
                list.Add(plyty);
                return View("ConfirmAdd", plyty);

            }
            else
            {
                return View("Add");
            }
        }
        public ActionResult FindAll()
        {
            return View("List", list);
        }
    }
}

13309zadanie1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

13309zadanie1/Views/Plyty/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model _13309zadanie1.Models.Plyty

<div class="container-fluid" m-3>
    <h2>Wpisz dane do zamówienia płyty</h2>
    <form asp-controller="Plyty" asp-action="Add" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mb-3">
            <span asp-validation-for="Szerokosc" class="text-danger"></span>
            <label asp-for="Szerokosc">Szerokość płyty w mm</label>
            <input class="form-control" asp-for="Szerokosc" />
        </div>
        <div class="mb-3">
            <span asp-validation-for="Wysokosc" class="text-danger"></span>
            <label asp-for="Wysokosc">Wysokość płyty w mm</label>
            <input class="form-control" asp-for="Wysokosc" />
        </div>
        <div class="mb-3">
            <span asp-validation-for="Cena" class="text-danger"></span>
            <label asp-for="Cena">Cena za 1 m^2</label>
            <input class="form-control" asp-for="Cena" />
        </div>
        <div class="mb-3">
            <span asp-validation-for="Ilosc" class="text-danger"></span>
            <label asp-for="Ilosc">Liczba w szt</label>
            <input class="form-control" asp-for="Ilosc" />
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Zapisz</button>
        </div>
    </form>
</div>

13309zadanie1/Views/Plyty/ConfirmAdd.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model _13309zadanie1.Models.Plyty
<h1>Zamówiłeś płytę meblową</h1>
<p>Zamówiłeś @Model.Ilosc płyt rozmiarem @Model.Wysokosc x @Model.Szerokosc</p>
<a asp-controller="Plyty" asp-action="FindAll">Zobacz liste płyt</a>
<a asp-controller="Plyty" asp-action="Add">Dodaj jeszcze płytę</a>

13309zadanie1/Views/Plyty/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Płyty meblowe</h1>
<a asp-controller="Plyty" asp-action="Add">Dodaj zamówienie</a><br />
<a asp-controller="Plyty" asp-action="FindAll">Zobacz listę zamówionych płyt</a>

13309zadanie1/Views/Plyty/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{

    decimal pole = 0;
    decimal cena = 0;
    decimal szerokosc = 0;
    decimal wysokosc = 0;
}
@model ICollection<_13309zadanie1.Models.Plyty>
<div class="container-fluid m-3">
    <h2>Zamówienie</h2>
    <table class="table">
        <tr>
            <td>Rozmiar</td>
            <td>Ilość sztuk</td>
            <td>Cena za całość</td>
        </tr>
        @foreach (var plyty in Model)
        {
            szerokosc = plyty.Szerokosc * 0.001M;
            wysokosc = plyty.Wysokosc * 0.001M;
            pole = szerokosc * wysokosc;
            cena = pole * plyty.Ilosc * plyty.Cena;
            <tr>
                
                <td>
                    @plyty.Szerokosc x @plyty.Wysokosc
                </td>
            
                
                <td>
                    @plyty.Ilosc
                </td>
            
                
                <td>
                    @cena.ToString("#,##0.##") zł
                </td>
            </tr>
        }

    </table>
</div>

13309zadanie1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _13309zadanie1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_13309zadanie1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plyty" asp-action="Index">Plyty</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - _13309zadanie1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>